### ISSUE TITLE
Example in mapreduce

### ISSUE THREAD

**Issue by NikhilrajKR** [yongtang/hadoop-xz#2]
``` java
Configuration conf = new Configuration();
conf.set("io.compression.codecs","io.sensesecure.hadoop.xz.XZCodec");
```

is it correct to do compression in mapreduce ? When i decompress it using java `XZInputStream`
the decompressed file is always empty.

Thanks

**Comment by SyncWorld** [comment]
Can you give the examples on the compression and decompression?

**Comment by NikhilrajKR** [comment]
I am using a simple json file as input

**Comment by SyncWorld** [comment]
OK, what about the code or command you used?

**Comment by NikhilrajKR** [comment]
For compressing

``` java
Configuration conf = new Configuration();
conf.setBoolean("mapred.output.compress", true);
conf.set("io.compression.codecs","io.sensesecure.hadoop.xz.XZCodec");
Job job = new Job(conf, "XZ Compression");
job.setJarByClass(XZExecutor.class);
job.setMapperClass(WordMapper.class);
job.setReducerClass(TranslationReducer.class);
job.setOutputKeyClass(Text.class);
job.setOutputValueClass(Text.class);
job.setMapOutputKeyClass(Text.class);
job.setMapOutputValueClass(Text.class);
job.setInputFormatClass(KeyValueTextInputFormat.class);
job.setOutputFormatClass(TextOutputFormat.class);
FileInputFormat.addInputPath(job, new Path("inputpath"));
FileOutputFormat.setOutputPath(job, new Path("outputpath"));
boolean result = job.waitForCompletion(true);
```

for decompressing the compressed .xz file

``` java
XZInputStream xzInputStream = new XZInputStream(bufferedInputStream);
FileOutputStream outputStream = new FileOutputStream("outputpath");
final byte[] buffer = new byte[8192];
int n = 0;
while (-1 != (n = xzInputStream.read(buffer))) {
        outputStream.write(buffer, 0, n);
}
outputStream.close();
xzInputStream.close();
```

**Comment by SyncWorld** [comment]
I tried your method, it's empty output. However, when I use following command:
/opt/tiger/yarn_deploy/hadoop-2.3.0-cdh5.1.0/bin/hadoop jar $HADOOP_STREAMING_JAR -libjars /home/yanlin/workspace/compress/hadoop-xz/target/hadoop-xz-1.5-SNAPSHOT.jar -Dmapred.output.compress=false -Dmapred.compress.map.out=false -Dmapred.output.compression.codec=io.sensesecure.hadoop.xz.XZCodec -Dmapred.map.tasks=1 -Dmapred.reduce.tasks=0  -input /tmp/lzma/test/ -output /tmp/lzma/test_origin -mapper "cat" -reducer "cat"
It just copies files. I'm seeking new solution, too.

**Comment by SyncWorld** [comment]
You should try XZSplitCompressionInputStream for decompression.

**Comment by yongtang** [comment]
Sorry for the late reply. Will take a look this weekend. ---yongtang

**Comment by yongtang** [comment]
The configuration mapred.output.compress is for old map reduce API (org.apache.hadoop.mapred) and is deprecated.

I used the configuration for new map reduce API (org.apache.hadoop.mapreduce) with Hadoop 2.6.0 and everything is fine:

``` java
Configuration conf = new Configuration();
conf.setBoolean("mapreduce.output.fileoutputformat.compress", true);
conf.set("mapreduce.output.fileoutputformat.compress.codec", "io.sensesecure.hadoop.xz.XZCodec");
```

In your output directory you will see two files:

``` sh
yongtang@ubuntu:~/wordcount$ /usr/local/hadoop/bin/hadoop fs -get Out
yongtang@ubuntu:~/wordcount$ ls Out/
part-r-00000.xz  _SUCCESS
```

The part-r-00000.xz is the compressed file. You could dump the uncompressed content with xz -d -c part-r-00000.xz.

**Comment by yongtang** [comment]
Closed for now. Please re-open if you encounter any other issues.
