### ISSUE TITLE
Can't save as sequence file

### ISSUE THREAD

**Issue by rishihahs** [yongtang/hadoop-xz#5]
Hi, the following command is throwing an `UnsupportedOperationException` from [XZCompressor](https://github.com/yongtang/hadoop-xz/blob/master/src/main/java/io/sensesecure/hadoop/xz/XZCompressor.java):

```
import org.apache.hadoop.io.Text
sc.parallelize(Array("1", "2", "3")).map(num => (new Text(num), new Text(num))).saveAsSequenceFile("<path>", Some(classOf[io.sensesecure.hadoop.xz.XZCodec]))
```

**Comment by yongtang** [comment]
Fixed through #8.
